/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f6fafe',
        'primary-fixed': '#dbe1ff',
        primary: '#004ccd',
        error: '#ba1a1a',
        'on-surface-variant': '#424656',
        'on-tertiary-container': '#fff1ed',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#00174c',
        'error-container': '#ffdad6',
        'on-background': '#171c1f',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#edf1f5',
        'surface-tint': '#0052dd',
        'secondary-fixed': '#cfe6f2',
        'on-secondary-fixed': '#071e27',
        'on-secondary-fixed-variant': '#354a53',
        'on-surface': '#171c1f',
        'primary-fixed-dim': '#b4c5ff',
        'on-error': '#ffffff',
        'tertiary-container': '#c84000',
        'secondary-container': '#cfe6f2',
        'secondary-fixed-dim': '#b4cad6',
        'surface-container-high': '#e4e9ed',
        outline: '#737687',
        'surface-dim': '#d6dade',
        'on-tertiary-fixed-variant': '#832700',
        'on-secondary-container': '#526772',
        'surface-container': '#eaeef2',
        tertiary: '#9e3100',
        surface: '#f6fafe',
        'inverse-surface': '#2c3134',
        'on-primary': '#ffffff',
        'outline-variant': '#c3c6d8',
        'surface-bright': '#f6fafe',
        'on-tertiary-fixed': '#390c00',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f8',
        'surface-container-highest': '#dfe3e7',
        'inverse-primary': '#b4c5ff',
        'primary-container': '#0f62fe',
        'tertiary-fixed-dim': '#ffb59d',
        'tertiary-fixed': '#ffdbd0',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#003da9',
        secondary: '#4c616c',
        'on-primary-container': '#f3f3ff',
        'surface-variant': '#dfe3e7',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xl: '32px',
        sm: '8px',
        lg: '24px',
        xs: '4px',
        'margin-mobile': '16px',
        gutter: '20px',
        md: '16px',
        base: '4px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'label-md': ['Inter'],
        'body-md': ['Inter'],
        'title-lg': ['Inter'],
        'display-lg': ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
